import { Grid, Paper, Typography } from "@mui/material";
import { Box } from "@mui/system";
import Head from "next/head";

const StatsPage = () => {
    return (
        <>
            <Head>
                <title>Savings | Cuan</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {/* <Grid container spacing={2}>
                <Grid item xs={12} mb={2}>
                    <Typography variant="h5" align="center">This Month Recap</Typography>
                </Grid>
                <Grid item xs={6} sx={{
                    border: '1px solid white',
                    p: '16px',
                    borderRadius: '8px',
                    // m: '8px 16px'
                }}>
                    <Typography align="center" children={"You Spend"} />
                    <Typography align="center" fontWeight="bold" children={`Rp. 200.000`} />
                </Grid>
                <Grid item xs={6} sx={{
                    border: '1px solid white',
                    p: '16px',
                    borderRadius: '8px',
                    // m: '8px 16px'
                }}>
                    <Typography align="center" children={"You Spend"} />
                    <Typography align="center" fontWeight="bold" children={`Rp. 200.000`} />
                </Grid>
                <Grid item xs={6} sx={{
                    border: '1px solid white',
                    p: '16px',
                    borderRadius: '8px',
                    // m: '8px 16px'
                }}>
                    <Typography align="center" children={"You Spend"} />
                    <Typography align="center" fontWeight="bold" children={`Rp. 200.000`} />
                </Grid>
                <Grid item xs={6} sx={{
                    border: '1px solid white',
                    p: '16px',
                    borderRadius: '8px',
                    // m: '8px 16px'
                }}>
                    <Typography align="center" children={"You Spend"} />
                    <Typography align="center" fontWeight="bold" children={`Rp. 200.000`} />
                </Grid>
            </Grid> */}
            <Grid container spacing={1} p="16px 24px">
                <Grid item xs={6}>
                    <Box sx={{
                        border: '1px solid white',
                        p: '16px',
                        borderRadius: '8px',
                        // m: '8px 16px'
                    }}>
                        <Typography align="center" children={"You Spend"} />
                        <Typography align="center" fontWeight="bold" children={`Rp. 200.000`} />
                    </Box>
                </Grid>
                <Grid item xs={6}>
                    <Box sx={{
                    border: '1px solid white',
                    p: '16px',
                    borderRadius: '8px',
                    // m: '8px 16px'
                }}>
                    <Typography align="center" children={"You Spend"} />
                    <Typography align="center" fontWeight="bold" children={`Rp. 200.000`} />
                </Box>
                </Grid>
                <Grid item xs={6}>
                    <Box sx={{
                    border: '1px solid white',
                    p: '16px',
                    borderRadius: '8px'
                }}>
                    <Typography align="center" children={"You Spend"} />
                    <Typography align="center" fontWeight="bold" children={`Rp. 200.000`} />
                </Box>
                </Grid>
                <Grid item xs={6}>
                    <Box sx={{
                    border: '1px solid white',
                    p: '16px',
                    borderRadius: '8px',
                }}>
                    <Typography align="center" children={"You Spend"} />
                    <Typography align="center" fontWeight="bold" children={`Rp. 200.000`} />
                </Box>
                </Grid>
            </Grid>
        </>
    );
}
 
export default StatsPage;