import Head from 'next/head'
import { Button, Typography } from '@mui/material'
import styles from '../styles/Home.module.css'
import AccountCircleIcon from '@mui/icons-material/AccountCircle';


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <Typography variant='h6' children="CUAN" />
        <AccountCircleIcon />
      </header>
    </>
  )
}
